### ISSUE TITLE
Only active in editor.

### ISSUE THREAD

**Issue by michaellegrand** [sanukin39/UniClipboard#2]
Hi, 
I recently added this to a production product, but had to modify the source because it worked on mobile and in editor, but not on desktop outside of the editor.

So in my case it worked on ios/android, but not steam.

We just made this minor change in UniClipboard.cs:

if (_board == null) {
                #if UNITY_ANDROID
                _board = new AndroidBoard();
                #elif UNITY_IOS
                _board = new IOSBoard ();
                #else
                _board = new EditorBoard();
                #endif
}

Was previously:

 if (_board == null) {
                #if UNITY_EDITOR
                _board = new EditorBoard();
                #elif UNITY_ANDROID
                _board = new AndroidBoard();
                #elif UNITY_IOS
                _board = new IOSBoard ();
                #endif
 }

Thanks for sharing this code with the community. Much appreciated. :)

**Comment by sanukin39** [comment]
Hi michaellegrand,
Sorry for late reply and thanks for your information!!
I added a steam support to the plugin at version 1.0.1.
